M48
; DRILL file {KiCad 7.99.0-1761-g0fd2efa283} date Tue Aug 22 00:03:22 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-22T00:03:22+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-1761-g0fd2efa283
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
%
G90
G05
T1
X88.56Y-102.71
X163.96Y-102.71
X163.96Y-136.71
T0
M30
